// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Login(Props) {
  return React.createElement("div", undefined, "Hello Login");
}

var make = Login;

export {
  make ,
  
}
/* react Not a pure module */
