// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.bs.js";

function NotFound(Props) {
  var url = ReasonReactRouter.useUrl(undefined, undefined);
  var pathList = List.map((function (path) {
          return React.createElement("div", undefined, path);
        }), url.path);
  var pathArr = $$Array.of_list(pathList);
  return React.createElement("div", undefined, "Page Not Found", pathArr);
}

var make = NotFound;

export {
  make ,
  
}
/* react Not a pure module */
