// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Register(Props) {
  return React.createElement("div", undefined, "Hello Register");
}

var make = Register;

export {
  make ,
  
}
/* react Not a pure module */
